#1 'Footer is Broken' corrected.
SmruthyJoseph/WordpressAssignment-1 pull request #3
Opened 2021-01-02 03:51 UTC by SmruthyJoseph

#1 '**Footer is Broken**' Corrected.

2021-01-02 09:22 UTC, AbhijithHaridas requested changes
@SmruthyJoseph please correct the changes

2021-01-02 09:22 UTC, AbhijithHaridas commented on index.html
> +
@SmruthyJoseph styles should not be included in the template using a style tag. Please move this to the CSS file

2021-01-02 09:31 UTC, AbhijithHaridas commented on index.html
> +
Why did this happen?

2021-01-02 09:33 UTC, SmruthyJoseph commented on index.html
> +
Ok, I will correct it.

2021-01-02 09:44 UTC, SmruthyJoseph commented on index.html
> +
The 'Google Font's size ' can't change if I put those codes in style.css. That's why I  put font styling in index page. Sorry I will correct them.

2021-01-06 11:49 UTC, SmruthyJoseph commented
#1 'Footer is Broken' Corrected.

2021-01-07 12:40 UTC, AbhijithHaridas requested changes
@SmruthyJoseph Why there are so many file changes that are not part of this issue?

2021-01-07 12:46 UTC, SmruthyJoseph commented
> @SmruthyJoseph Why there are so many file changes that are not part of this issue?
Sorry, I pushed all files accidentally.

2021-01-07 12:47 UTC, AbhijithHaridas commented
This should not happen again and I need this corrected today itself

2021-01-07 13:11 UTC, SmruthyJoseph commented
> This should not happen again and I need this corrected today itself

Ok.

2021-01-08 07:49 UTC, AbhijithHaridas commented
### Disqualified

2021-01-08 07:49 UTC, closed without merging